modLoader    = "javafml"
loaderVersion= "[47,)"
license      = "MIT"

[[mods]]
modId        = "ultimatehotbars"
version      = "${mod_version}" # ← now automatically filled
displayName  = "UltimateHotbars"
description  = '''
  A Forge mod that gives you virtually unlimited hotbars!
'''
authors      = ["Ross Morgenstern"]

[[dependencies.ultimatehotbars]]
modId       = "minecraft"
mandatory   = true
versionRange= "[1.20.1,)"
ordering    = "NONE"
side        = "CLIENT"

[[dependencies.ultimatehotbars]]
modId       = "forge"
mandatory   = false
versionRange= "[47,)"
ordering    = "NONE"
side        = "CLIENT"
